In [1]:
print("hello")

hello

In [5]:
# Step 1: Import Required Libraries

from pathlib import Path
import numpy as np
import pandas as pd

In [6]:
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [7]:
from sklearn.model_selection import train_test_split
print("sklearn model_selection imported")

sklearn model_selection imported

In [8]:
from sklearn.preprocessing import StandardScaler
print("StandardScaler imported")

StandardScaler imported

In [9]:
plt.style.use("ggplot")

In [10]:
#Step 2 – Create Feature Engineered Folder
feature_folder = Path("feature_engineered")
feature_folder.mkdir(exist_ok=True)
print(feature_folder)

feature_engineered

In [ ]:
#Step 3 – Locate-Processed Files
processed_2019 = Path("processed_2019")
processed_2020 = Path("processed_2020")

files_2019 = sorted(processed_2019.glob("*.parquet"))
files_2020 = sorted(processed_2020.glob("*.parquet"))

print("2019 Files :", len(files_2019))
print("2020 Files :", len(files_2020))

2019 Files : 2920
2020 Files : 1776

In [12]:
#Step 4 - Wind Speed Function
def calculate_wind_speed(df):

    df = df.copy()

    df["wind_speed"] = np.sqrt(
        df["u_wind"]**2 +
        df["v_wind"]**2
    )

    return df

In [13]:
#Step 5 - Wind Direction Function
def calculate_wind_direction(df):

    df = df.copy()

    direction = (
        270 -
        np.degrees(
            np.arctan2(
                df["v_wind"],
                df["u_wind"]
            )
        )
    ) % 360

    df["wind_direction"] = direction

    return df

In [14]:
#Step 6 – Time Feature Engineering
def create_time_features(df):

    df = df.copy()

    df["time"] = pd.to_datetime(
        df["time"],
        format="%Y%m%d%H"
    )

    df["year"] = df["time"].dt.year

    df["month"] = df["time"].dt.month

    df["day"] = df["time"].dt.day

    df["hour"] = df["time"].dt.hour

    return df

In [15]:
#Step 7 - Season feature engineering
def create_season(df):

    df = df.copy()

    season_map = {
        12: "Winter",
        1: "Winter",
        2: "Winter",
        3: "Spring",
        4: "Spring",
        5: "Spring",
        6: "Summer",
        7: "Summer",
        8: "Summer",
        9: "Autumn",
        10: "Autumn",
        11: "Autumn"
    }

    df["season"] = df["month"].map(season_map)

    return df

In [16]:
#Step 8 – Complete Feature Engineering Function
def engineer_features(df):

    df = calculate_wind_speed(df)

    df = calculate_wind_direction(df)

    df = create_time_features(df)

    df = create_season(df)

    return df

In [17]:
#Step - 9 Test on One File
sample = pd.read_parquet(
    files_2020[0]
)

sample = engineer_features(sample)

sample.head()

,time,pressure_hpa,latitude,longitude,geopotential_height,temperature,relative_humidity,u_wind,v_wind,wind_speed,wind_direction,year,month,day,hour,season
0,2020-01-01,50.0,-15.0,33.96,20731.246094,208.090027,3.403575,-5.746175,-0.919383,5.819260,80.909760,2020,1,1,0,Winter
1,2020-01-01,50.0,-15.0,34.08,20819.746094,209.363464,2.856700,-5.824300,-0.216258,5.828313,87.873535,2020,1,1,0,Winter
2,2020-01-01,50.0,-15.0,34.20,20772.246094,208.793152,3.122325,-5.386800,-0.935008,5.467344,80.153046,2020,1,1,0,Winter
3,2020-01-01,50.0,-15.0,34.32,20539.246094,205.754089,4.716075,-3.996175,-2.966258,4.976756,53.414429,2020,1,1,0,Winter
4,2020-01-01,50.0,-15.0,34.44,20399.246094,203.941589,6.075450,-2.168050,-4.638133,5.119836,25.053284,2020,1,1,0,Winter

In [18]:
#Step 10 - check columns
sample.columns

Index(['time', 'pressure_hpa', 'latitude', 'longitude', 'geopotential_height',
       'temperature', 'relative_humidity', 'u_wind', 'v_wind', 'wind_speed',
       'wind_direction', 'year', 'month', 'day', 'hour', 'season'],
      dtype='str')

In [19]:
#Step 11 - Save one file
sample.to_parquet(
    feature_folder / "sample.parquet",
    index=False
)

In [20]:
#Step 12 – Process Entire Dataset
all_files = files_2019 + files_2020

failed = []

for i, file in enumerate(all_files):

    print(f"[{i+1}/{len(all_files)}] {file.name}")

    try:

        df = pd.read_parquet(file)

        df = engineer_features(df)

        output = feature_folder / file.name

        df.to_parquet(
            output,
            index=False
        )

    except Exception as e:

        failed.append((file.name, str(e)))

print("\nCompleted")

print("Failed :", len(failed))

[1/4696] 2019010100.parquet
[2/4696] 2019010103.parquet
[3/4696] 2019010106.parquet
[4/4696] 2019010109.parquet
[5/4696] 2019010112.parquet
[6/4696] 2019010115.parquet
[7/4696] 2019010118.parquet
[8/4696] 2019010121.parquet
[9/4696] 2019010200.parquet
[10/4696] 2019010203.parquet
[11/4696] 2019010206.parquet
[12/4696] 2019010209.parquet
[13/4696] 2019010212.parquet
[14/4696] 2019010215.parquet
[15/4696] 2019010218.parquet
[16/4696] 2019010221.parquet
[17/4696] 2019010300.parquet
[18/4696] 2019010303.parquet
[19/4696] 2019010306.parquet
[20/4696] 2019010309.parquet
[21/4696] 2019010312.parquet
[22/4696] 2019010315.parquet
[23/4696] 2019010318.parquet
[24/4696] 2019010321.parquet
[25/4696] 2019010400.parquet
[26/4696] 2019010403.parquet
[27/4696] 2019010406.parquet
[28/4696] 2019010409.parquet
[29/4696] 2019010412.parquet
[30/4696] 2019010415.parquet
[31/4696] 2019010418.parquet
[32/4696] 2019010421.parquet
[33/4696] 2019010500.parquet
[34/4696] 2019010503.parquet
[35/4696] 2019010506.parquet
[36/4696] 2019010509.parquet
[37/4696] 2019010512.parquet
[38/4696] 2019010515.parquet
[39/4696] 2019010518.parquet
[40/4696] 2019010521.parquet
[41/4696] 2019010600.parquet
[42/4696] 2019010603.parquet
[43/4696] 2019010606.parquet
[44/4696] 2019010609.parquet
[45/4696] 2019010612.parquet
[46/4696] 2019010615.parquet
[47/4696] 2019010618.parquet
[48/4696] 2019010621.parquet
[49/4696] 2019010700.parquet
[50/4696] 2019010703.parquet
[51/4696] 2019010706.parquet
[52/4696] 2019010709.parquet
[53/4696] 2019010712.parquet
[54/4696] 2019010715.parquet
[55/4696] 2019010718.parquet
[56/4696] 2019010721.parquet
[57/4696] 2019010800.parquet
[58/4696] 2019010803.parquet
[59/4696] 2019010806.parquet
[60/4696] 2019010809.parquet
[61/4696] 2019010812.parquet
[62/4696] 2019010815.parquet
[63/4696] 2019010818.parquet
[64/4696] 2019010821.parquet
[65/4696] 2019010900.parquet
[66/4696] 2019010903.parquet
[67/4696] 2019010906.parquet
[68/4696] 2019010909.parquet
[69/4696] 2019010912.parquet
[70/4696] 2019010915.parquet
[71/4696] 2019010918.parquet
[72/4696] 2019010921.parquet
[73/4696] 2019011000.parquet
[74/4696] 2019011003.parquet
[75/4696] 2019011006.parquet
[76/4696] 2019011009.parquet
[77/4696] 2019011012.parquet
[78/4696] 2019011015.parquet
[79/4696] 2019011018.parquet
[80/4696] 2019011021.parquet
[81/4696] 2019011100.parquet
[82/4696] 2019011103.parquet
[83/4696] 2019011106.parquet
[84/4696] 2019011109.parquet
[85/4696] 2019011112.parquet
[86/4696] 2019011115.parquet
[87/4696] 2019011118.parquet
[88/4696] 2019011121.parquet
[89/4696] 2019011200.parquet
[90/4696] 2019011203.parquet
[91/4696] 2019011206.parquet
[92/4696] 2019011209.parquet
[93/4696] 2019011212.parquet
[94/4696] 2019011215.parquet
[95/4696] 2019011218.parquet
[96/4696] 2019011221.parquet
[97/4696] 2019011300.parquet
[98/4696] 2019011303.parquet
[99/4696] 2019011306.parquet
[100/4696] 2019011309.parquet
[101/4696] 2019011312.parquet
[102/4696] 2019011315.parquet
[103/4696] 2019011318.parquet
[104/4696] 2019011321.parquet
[105/4696] 2019011400.parquet
[106/4696] 2019011403.parquet
[107/4696] 2019011406.parquet
[108/4696] 2019011409.parquet
[109/4696] 2019011412.parquet
[110/4696] 2019011415.parquet
[111/4696] 2019011418.parquet
[112/4696] 2019011421.parquet
[113/4696] 2019011500.parquet
[114/4696] 2019011503.parquet
[115/4696] 2019011506.parquet
[116/4696] 2019011509.parquet
[117/4696] 2019011512.parquet
[118/4696] 2019011515.parquet
[119/4696] 2019011518.parquet
[120/4696] 2019011521.parquet
[121/4696] 2019011600.parquet
[122/4696] 2019011603.parquet
[123/4696] 2019011606.parquet
[124/4696] 2019011609.parquet
[125/4696] 2019011612.parquet
[126/4696] 2019011615.parquet
[127/4696] 2019011618.parquet
[128/4696] 2019011621.parquet
[129/4696] 2019011700.parquet
[130/4696] 2019011703.parquet
[131/4696] 2019011706.parquet
[132/4696] 2019011709.parquet
[133/4696] 2019011712.parquet
[134/4696] 2019011715.parquet
[135/4696] 2019011718.parquet
[136/4696] 2019011721.parquet
[137/4696] 2019011800.parquet
[138/4696] 2019011803.parquet
[139/4696] 2019011806.parquet
[140/4696] 2019011809.parquet
[141/4696] 2019011812.parquet
[142/4696] 2019011815.parquet
[143/4696] 2019011818.parquet
[144/4696] 2019011821.parquet
[145/4696] 2019011900.parquet
[146/4696] 2019011903.parquet
[147/4696] 2019011906.parquet
[148/4696] 2019011909.parquet
[149/4696] 2019011912.parquet
[150/4696] 2019011915.parquet
[151/4696] 2019011918.parquet
[152/4696] 2019011921.parquet
[153/4696] 2019012000.parquet
[154/4696] 2019012003.parquet
[155/4696] 2019012006.parquet
[156/4696] 2019012009.parquet
[157/4696] 2019012012.parquet
[158/4696] 2019012015.parquet
[159/4696] 2019012018.parquet
[160/4696] 2019012021.parquet
[161/4696] 2019012100.parquet
[162/4696] 2019012103.parquet
[163/4696] 2019012106.parquet
[164/4696] 2019012109.parquet
[165/4696] 2019012112.parquet
[166/4696] 2019012115.parquet
[167/4696] 2019012118.parquet
[168/4696] 2019012121.parquet
[169/4696] 2019012200.parquet
[170/4696] 2019012203.parquet
[171/4696] 2019012206.parquet
[172/4696] 2019012209.parquet
[173/4696] 2019012212.parquet
[174/4696] 2019012215.parquet
[175/4696] 2019012218.parquet
[176/4696] 2019012221.parquet
[177/4696] 2019012300.parquet
[178/4696] 2019012303.parquet
[179/4696] 2019012306.parquet
[180/4696] 2019012309.parquet
[181/4696] 2019012312.parquet
[182/4696] 2019012315.parquet
[183/4696] 2019012318.parquet
[184/4696] 2019012321.parquet
[185/4696] 2019012400.parquet
[186/4696] 2019012403.parquet
[187/4696] 2019012406.parquet
[188/4696] 2019012409.parquet
[189/4696] 2019012412.parquet
[190/4696] 2019012415.parquet
[191/4696] 2019012418.parquet
[192/4696] 2019012421.parquet
[193/4696] 2019012500.parquet
[194/4696] 2019012503.parquet
[195/4696] 2019012506.parquet
[196/4696] 2019012509.parquet
[197/4696] 2019012512.parquet
[198/4696] 2019012515.parquet
[199/4696] 2019012518.parquet
[200/4696] 2019012521.parquet
[201/4696] 2019012600.parquet
[202/4696] 2019012603.parquet
[203/4696] 2019012606.parquet
[204/4696] 2019012609.parquet
[205/4696] 2019012612.parquet
[206/4696] 2019012615.parquet
[207/4696] 2019012618.parquet
[208/4696] 2019012621.parquet
[209/4696] 2019012700.parquet
[210/4696] 2019012703.parquet
[211/4696] 2019012706.parquet
[212/4696] 2019012709.parquet
[213/4696] 2019012712.parquet
[214/4696] 2019012715.parquet
[215/4696] 2019012718.parquet
[216/4696] 2019012721.parquet
[217/4696] 2019012800.parquet
[218/4696] 2019012803.parquet
[219/4696] 2019012806.parquet
[220/4696] 2019012809.parquet
[221/4696] 2019012812.parquet
[222/4696] 2019012815.parquet
[223/4696] 2019012818.parquet
[224/4696] 2019012821.parquet
[225/4696] 2019012900.parquet
[226/4696] 2019012903.parquet
[227/4696] 2019012906.parquet
[228/4696] 2019012909.parquet
[229/4696] 2019012912.parquet
[230/4696] 2019012915.parquet
[231/4696] 2019012918.parquet
[232/4696] 2019012921.parquet
[233/4696] 2019013000.parquet
[234/4696] 2019013003.parquet
[235/4696] 2019013006.parquet
[236/4696] 2019013009.parquet
[237/4696] 2019013012.parquet
[238/4696] 2019013015.parquet
[239/4696] 2019013018.parquet
[240/4696] 2019013021.parquet
[241/4696] 2019013100.parquet
[242/4696] 2019013103.parquet
[243/4696] 2019013106.parquet
[244/4696] 2019013109.parquet
[245/4696] 2019013112.parquet
[246/4696] 2019013115.parquet
[247/4696] 2019013118.parquet
[248/4696] 2019013121.parquet
[249/4696] 2019020100.parquet
[250/4696] 2019020103.parquet
[251/4696] 2019020106.parquet
[252/4696] 2019020109.parquet
[253/4696] 2019020112.parquet
[254/4696] 2019020115.parquet
[255/4696] 2019020118.parquet
[256/4696] 2019020121.parquet
[257/4696] 2019020200.parquet
[258/4696] 2019020203.parquet
[259/4696] 2019020206.parquet
[260/4696] 2019020209.parquet
[261/4696] 2019020212.parquet
[262/4696] 2019020215.parquet
[263/4696] 2019020218.parquet
[264/4696] 2019020221.parquet
[265/4696] 2019020300.parquet
[266/4696] 2019020303.parquet
[267/4696] 2019020306.parquet
[268/4696] 2019020309.parquet
[269/4696] 2019020312.parquet
[270/4696] 2019020315.parquet
[271/4696] 2019020318.parquet
[272/4696] 2019020321.parquet
[273/4696] 2019020400.parquet
[274/4696] 2019020403.parquet
[275/4696] 2019020406.parquet
[276/4696] 2019020409.parquet
[277/4696] 2019020412.parquet
[278/4696] 2019020415.parquet
[279/4696] 2019020418.parquet
[280/4696] 2019020421.parquet
[281/4696] 2019020500.parquet
[282/4696] 2019020503.parquet
[283/4696] 2019020506.parquet
[284/4696] 2019020509.parquet
[285/4696] 2019020512.parquet
[286/4696] 2019020515.parquet
[287/4696] 2019020518.parquet
[288/4696] 2019020521.parquet
[289/4696] 2019020600.parquet
[290/4696] 2019020603.parquet
[291/4696] 2019020606.parquet
[292/4696] 2019020609.parquet
[293/4696] 2019020612.parquet
[294/4696] 2019020615.parquet
[295/4696] 2019020618.parquet
[296/4696] 2019020621.parquet
[297/4696] 2019020700.parquet
[298/4696] 2019020703.parquet
[299/4696] 2019020706.parquet
[300/4696] 2019020709.parquet
[301/4696] 2019020712.parquet
[302/4696] 2019020715.parquet
[303/4696] 2019020718.parquet
[304/4696] 2019020721.parquet
[305/4696] 2019020800.parquet
[306/4696] 2019020803.parquet
[307/4696] 2019020806.parquet
[308/4696] 2019020809.parquet
[309/4696] 2019020812.parquet
[310/4696] 2019020815.parquet
[311/4696] 2019020818.parquet
[312/4696] 2019020821.parquet
[313/4696] 2019020900.parquet
[314/4696] 2019020903.parquet
[315/4696] 2019020906.parquet
[316/4696] 2019020909.parquet
[317/4696] 2019020912.parquet
[318/4696] 2019020915.parquet
[319/4696] 2019020918.parquet
[320/4696] 2019020921.parquet
[321/4696] 2019021000.parquet
[322/4696] 2019021003.parquet
[323/4696] 2019021006.parquet
[324/4696] 2019021009.parquet
[325/4696] 2019021012.parquet
[326/4696] 2019021015.parquet
[327/4696] 2019021018.parquet
[328/4696] 2019021021.parquet
[329/4696] 2019021100.parquet
[330/4696] 2019021103.parquet
[331/4696] 2019021106.parquet
[332/4696] 2019021109.parquet
[333/4696] 2019021112.parquet
[334/4696] 2019021115.parquet
[335/4696] 2019021118.parquet
[336/4696] 2019021121.parquet
[337/4696] 2019021200.parquet
[338/4696] 2019021203.parquet
[339/4696] 2019021206.parquet
[340/4696] 2019021209.parquet
[341/4696] 2019021212.parquet
[342/4696] 2019021215.parquet
[343/4696] 2019021218.parquet
[344/4696] 2019021221.parquet
[345/4696] 2019021300.parquet
[346/4696] 2019021303.parquet
[347/4696] 2019021306.parquet
[348/4696] 2019021309.parquet
[349/4696] 2019021312.parquet
[350/4696] 2019021315.parquet
[351/4696] 2019021318.parquet
[352/4696] 2019021321.parquet
[353/4696] 2019021400.parquet
[354/4696] 2019021403.parquet
[355/4696] 2019021406.parquet
[356/4696] 2019021409.parquet
[357/4696] 2019021412.parquet
[358/4696] 2019021415.parquet
[359/4696] 2019021418.parquet
[360/4696] 2019021421.parquet
[361/4696] 2019021500.parquet
[362/4696] 2019021503.parquet
[363/4696] 2019021506.parquet
[364/4696] 2019021509.parquet
[365/4696] 2019021512.parquet
[366/4696] 2019021515.parquet
[367/4696] 2019021518.parquet
[368/4696] 2019021521.parquet
[369/4696] 2019021600.parquet
[370/4696] 2019021603.parquet
[371/4696] 2019021606.parquet
[372/4696] 2019021609.parquet
[373/4696] 2019021612.parquet
[374/4696] 2019021615.parquet
[375/4696] 2019021618.parquet
[376/4696] 2019021621.parquet
[377/4696] 2019021700.parquet
[378/4696] 2019021703.parquet
[379/4696] 2019021706.parquet
[380/4696] 2019021709.parquet
[381/4696] 2019021712.parquet
[382/4696] 2019021715.parquet
[383/4696] 2019021718.parquet
[384/4696] 2019021721.parquet
[385/4696] 2019021800.parquet
[386/4696] 2019021803.parquet
[387/4696] 2019021806.parquet
[388/4696] 2019021809.parquet
[389/4696] 2019021812.parquet
[390/4696] 2019021815.parquet
[391/4696] 2019021818.parquet
[392/4696] 2019021821.parquet
[393/4696] 2019021900.parquet
[394/4696] 2019021903.parquet
[395/4696] 2019021906.parquet
[396/4696] 2019021909.parquet
[397/4696] 2019021912.parquet
[398/4696] 2019021915.parquet
[399/4696] 2019021918.parquet
[400/4696] 2019021921.parquet
[401/4696] 2019022000.parquet
[402/4696] 2019022003.parquet
[403/4696] 2019022006.parquet
[404/4696] 2019022009.parquet
[405/4696] 2019022012.parquet
[406/4696] 2019022015.parquet
[407/4696] 2019022018.parquet
[408/4696] 2019022021.parquet
[409/4696] 2019022100.parquet
[410/4696] 2019022103.parquet
[411/4696] 2019022106.parquet
[412/4696] 2019022109.parquet
[413/4696] 2019022112.parquet
[414/4696] 2019022115.parquet
[415/4696] 2019022118.parquet
[416/4696] 2019022121.parquet
[417/4696] 2019022200.parquet
[418/4696] 2019022203.parquet
[419/4696] 2019022206.parquet
[420/4696] 2019022209.parquet
[421/4696] 2019022212.parquet
[422/4696] 2019022215.parquet
[423/4696] 2019022218.parquet
[424/4696] 2019022221.parquet
[425/4696] 2019022300.parquet
[426/4696] 2019022303.parquet
[427/4696] 2019022306.parquet
[428/4696] 2019022309.parquet
[429/4696] 2019022312.parquet
[430/4696] 2019022315.parquet
[431/4696] 2019022318.parquet
[432/4696] 2019022321.parquet
[433/4696] 2019022400.parquet
[434/4696] 2019022403.parquet
[435/4696] 2019022406.parquet
[436/4696] 2019022409.parquet
[437/4696] 2019022412.parquet
[438/4696] 2019022415.parquet
[439/4696] 2019022418.parquet
[440/4696] 2019022421.parquet
[441/4696] 2019022500.parquet
[442/4696] 2019022503.parquet
[443/4696] 2019022506.parquet
[444/4696] 2019022509.parquet
[445/4696] 2019022512.parquet
[446/4696] 2019022515.parquet
[447/4696] 2019022518.parquet
[448/4696] 2019022521.parquet
[449/4696] 2019022600.parquet
[450/4696] 2019022603.parquet
[451/4696] 2019022606.parquet
[452/4696] 2019022609.parquet
[453/4696] 2019022612.parquet
[454/4696] 2019022615.parquet
[455/4696] 2019022618.parquet
[456/4696] 2019022621.parquet
[457/4696] 2019022700.parquet
[458/4696] 2019022703.parquet
[459/4696] 2019022706.parquet
[460/4696] 2019022709.parquet
[461/4696] 2019022712.parquet
[462/4696] 2019022715.parquet
[463/4696] 2019022718.parquet
[464/4696] 2019022721.parquet
[465/4696] 2019022800.parquet
[466/4696] 2019022803.parquet
[467/4696] 2019022806.parquet
[468/4696] 2019022809.parquet
[469/4696] 2019022812.parquet
[470/4696] 2019022815.parquet
[471/4696] 2019022818.parquet
[472/4696] 2019022821.parquet
[473/4696] 2019030100.parquet
[474/4696] 2019030103.parquet
[475/4696] 2019030106.parquet
[476/4696] 2019030109.parquet
[477/4696] 2019030112.parquet
[478/4696] 2019030115.parquet
[479/4696] 2019030118.parquet
[480/4696] 2019030121.parquet
[481/4696] 2019030200.parquet
[482/4696] 2019030203.parquet
[483/4696] 2019030206.parquet
[484/4696] 2019030209.parquet
[485/4696] 2019030212.parquet
[486/4696] 2019030215.parquet
[487/4696] 2019030218.parquet
[488/4696] 2019030221.parquet
[489/4696] 2019030300.parquet
[490/4696] 2019030303.parquet
[491/4696] 2019030306.parquet
[492/4696] 2019030309.parquet
[493/4696] 2019030312.parquet
[494/4696] 2019030315.parquet
[495/4696] 2019030318.parquet
[496/4696] 2019030321.parquet
[497/4696] 2019030400.parquet
[498/4696] 2019030403.parquet
[499/4696] 2019030406.parquet
[500/4696] 2019030409.parquet
[501/4696] 2019030412.parquet
[502/4696] 2019030415.parquet
[503/4696] 2019030418.parquet
[504/4696] 2019030421.parquet
[505/4696] 2019030500.parquet
[506/4696] 2019030503.parquet
[507/4696] 2019030506.parquet
[508/4696] 2019030509.parquet
[509/4696] 2019030512.parquet
[510/4696] 2019030515.parquet
[511/4696] 2019030518.parquet
[512/4696] 2019030521.parquet
[513/4696] 2019030600.parquet
[514/4696] 2019030603.parquet
[515/4696] 2019030606.parquet
[516/4696] 2019030609.parquet
[517/4696] 2019030612.parquet
[518/4696] 2019030615.parquet
[519/4696] 2019030618.parquet
[520/4696] 2019030621.parquet
[521/4696] 2019030700.parquet
[522/4696] 2019030703.parquet
[523/4696] 2019030706.parquet
[524/4696] 2019030709.parquet
[525/4696] 2019030712.parquet
[526/4696] 2019030715.parquet
[527/4696] 2019030718.parquet
[528/4696] 2019030721.parquet
[529/4696] 2019030800.parquet
[530/4696] 2019030803.parquet
[531/4696] 2019030806.parquet
[532/4696] 2019030809.parquet
[533/4696] 2019030812.parquet
[534/4696] 2019030815.parquet
[535/4696] 2019030818.parquet
[536/4696] 2019030821.parquet
[537/4696] 2019030900.parquet
[538/4696] 2019030903.parquet
[539/4696] 2019030906.parquet
[540/4696] 2019030909.parquet
[541/4696] 2019030912.parquet
[542/4696] 2019030915.parquet
[543/4696] 2019030918.parquet
[544/4696] 2019030921.parquet
[545/4696] 2019031000.parquet
[546/4696] 2019031003.parquet
[547/4696] 2019031006.parquet
[548/4696] 2019031009.parquet
[549/4696] 2019031012.parquet
[550/4696] 2019031015.parquet
[551/4696] 2019031018.parquet
[552/4696] 2019031021.parquet
[553/4696] 2019031100.parquet
[554/4696] 2019031103.parquet
[555/4696] 2019031106.parquet
[556/4696] 2019031109.parquet
[557/4696] 2019031112.parquet
[558/4696] 2019031115.parquet
[559/4696] 2019031118.parquet
[560/4696] 2019031121.parquet
[561/4696] 2019031200.parquet
[562/4696] 2019031203.parquet
[563/4696] 2019031206.parquet
[564/4696] 2019031209.parquet
[565/4696] 2019031212.parquet
[566/4696] 2019031215.parquet
[567/4696] 2019031218.parquet
[568/4696] 2019031221.parquet
[569/4696] 2019031300.parquet
[570/4696] 2019031303.parquet
[571/4696] 2019031306.parquet
[572/4696] 2019031309.parquet
[573/4696] 2019031312.parquet
[574/4696] 2019031315.parquet
[575/4696] 2019031318.parquet
[576/4696] 2019031321.parquet
[577/4696] 2019031400.parquet
[578/4696] 2019031403.parquet
[579/4696] 2019031406.parquet
[580/4696] 2019031409.parquet
[581/4696] 2019031412.parquet
[582/4696] 2019031415.parquet
[583/4696] 2019031418.parquet
[584/4696] 2019031421.parquet
[585/4696] 2019031500.parquet
[586/4696] 2019031503.parquet
[587/4696] 2019031506.parquet
[588/4696] 2019031509.parquet
[589/4696] 2019031512.parquet
[590/4696] 2019031515.parquet
[591/4696] 2019031518.parquet
[592/4696] 2019031521.parquet
[593/4696] 2019031600.parquet
[594/4696] 2019031603.parquet
[595/4696] 2019031606.parquet
[596/4696] 2019031609.parquet
[597/4696] 2019031612.parquet
[598/4696] 2019031615.parquet
[599/4696] 2019031618.parquet
[600/4696] 2019031621.parquet
[601/4696] 2019031700.parquet
[602/4696] 2019031703.parquet
[603/4696] 2019031706.parquet
[604/4696] 2019031709.parquet
[605/4696] 2019031712.parquet
[606/4696] 2019031715.parquet
[607/4696] 2019031718.parquet
[608/4696] 2019031721.parquet
[609/4696] 2019031800.parquet
[610/4696] 2019031803.parquet
[611/4696] 2019031806.parquet
[612/4696] 2019031809.parquet
[613/4696] 2019031812.parquet
[614/4696] 2019031815.parquet
[615/4696] 2019031818.parquet
[616/4696] 2019031821.parquet
[617/4696] 2019031900.parquet
[618/4696] 2019031903.parquet
[619/4696] 2019031906.parquet
[620/4696] 2019031909.parquet
[621/4696] 2019031912.parquet
[622/4696] 2019031915.parquet
[623/4696] 2019031918.parquet
[624/4696] 2019031921.parquet
[625/4696] 2019032000.parquet
[626/4696] 2019032003.parquet
[627/4696] 2019032006.parquet
[628/4696] 2019032009.parquet
[629/4696] 2019032012.parquet
[630/4696] 2019032015.parquet
[631/4696] 2019032018.parquet
[632/4696] 2019032021.parquet
[633/4696] 2019032100.parquet
[634/4696] 2019032103.parquet
[635/4696] 2019032106.parquet
[636/4696] 2019032109.parquet
[637/4696] 2019032112.parquet
[638/4696] 2019032115.parquet
[639/4696] 2019032118.parquet
[640/4696] 2019032121.parquet
[641/4696] 2019032200.parquet
[642/4696] 2019032203.parquet
[643/4696] 2019032206.parquet
[644/4696] 2019032209.parquet
[645/4696] 2019032212.parquet
[646/4696] 2019032215.parquet
[647/4696] 2019032218.parquet
[648/4696] 2019032221.parquet
[649/4696] 2019032300.parquet
[650/4696] 2019032303.parquet
[651/4696] 2019032306.parquet
[652/4696] 2019032309.parquet
[653/4696] 2019032312.parquet
[654/4696] 2019032315.parquet
[655/4696] 2019032318.parquet
[656/4696] 2019032321.parquet
[657/4696] 2019032400.parquet
[658/4696] 2019032403.parquet
[659/4696] 2019032406.parquet
[660/4696] 2019032409.parquet
[661/4696] 2019032412.parquet
[662/4696] 2019032415.parquet
[663/4696] 2019032418.parquet
[664/4696] 2019032421.parquet
[665/4696] 2019032500.parquet
[666/4696] 2019032503.parquet
[667/4696] 2019032506.parquet
[668/4696] 2019032509.parquet
[669/4696] 2019032512.parquet
[670/4696] 2019032515.parquet

In [21]:
#verifying the files
len(list(feature_folder.glob("*.parquet")))

4697

In [24]:
# Inspect one feature-engineered file

sample = pd.read_parquet(next(feature_folder.glob("*.parquet")))

print("Shape:", sample.shape)

sample.head()

Shape: (1833005, 16)

,time,pressure_hpa,latitude,longitude,geopotential_height,temperature,relative_humidity,u_wind,v_wind,wind_speed,wind_direction,year,month,day,hour,season
0,2019-01-01,50.0,-15.0,33.96,20456.568359,202.932434,4.554688,-17.626209,0.869842,17.647659,92.825226,2019,1,1,0,Winter
1,2019-01-01,50.0,-15.0,34.08,20534.068359,203.994934,3.902344,-17.485584,0.885467,17.507990,92.898987,2019,1,1,0,Winter
2,2019-01-01,50.0,-15.0,34.20,20623.568359,205.182434,3.277344,-17.516834,1.033904,17.547319,93.377884,2019,1,1,0,Winter
3,2019-01-01,50.0,-15.0,34.32,20716.568359,206.338684,2.769531,-17.501209,1.174529,17.540577,93.839447,2019,1,1,0,Winter
4,2019-01-01,50.0,-15.0,34.44,20715.068359,206.190247,2.855469,-16.782459,1.315154,16.833912,94.480820,2019,1,1,0,Winter

In [25]:
sample.dtypes

time                   datetime64[ns]
pressure_hpa                  float64
latitude                      float64
longitude                     float64
geopotential_height           float32
temperature                   float32
relative_humidity             float32
u_wind                        float32
v_wind                        float32
wind_speed                    float32
wind_direction                float32
year                            int32
month                           int32
day                             int32
hour                            int32
season                            str
dtype: object

In [26]:
sample.isnull().sum()

time                   0
pressure_hpa           0
latitude               0
longitude              0
geopotential_height    0
temperature            0
relative_humidity      0
u_wind                 0
v_wind                 0
wind_speed             0
wind_direction         0
year                   0
month                  0
day                    0
hour                   0
season                 0
dtype: int64

In [27]:
sample["wind_speed"].describe()

count    1.833005e+06
mean     1.879911e+01
std      1.384493e+01
min      1.687050e-03
25%      8.369844e+00
50%      1.487819e+01
75%      2.550017e+01
max      8.798804e+01
Name: wind_speed, dtype: float64

In [28]:
sample["wind_direction"].describe()

count    1.833005e+06
mean     2.004521e+02
std      9.225747e+01
min      0.000000e+00
25%      9.431104e+01
50%      2.532063e+02
75%      2.713119e+02
max      3.599220e+02
Name: wind_direction, dtype: float64